### ISSUE TITLE
【Bug】除了清除文件和链接 其他功能无法使用

### ISSUE THREAD

**Issue by likemuuxi** [Yaozhuwa/AttachFlow#3]
已关闭其他所有插件调试
图片链接：![[../../Apparatus/Attachments/Assets/UML-240124-1.png]]

### 控制台消息
复制到剪切板：
plugin:attachment-flow-plugin:237 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'vault')
at eval (plugin:attachment-flow-plugin:237:25)
at Generator.next ()
at eval (plugin:attachment-flow-plugin:40:61)
at new Promise ()
at __async (plugin:attachment-flow-plugin:24:10)
at handlerCopyFile (plugin:attachment-flow-plugin:235:60)
at AttachFlowPlugin.eval (plugin:attachment-flow-plugin:626:11)
at Generator.next ()
at eval (plugin:attachment-flow-plugin:40:61)
at new Promise ()
使用默认应用打开：
plugin:attachment-flow-plugin:631 Uncaught TypeError: Cannot read properties of undefined (reading 'path')
at eval (plugin:attachment-flow-plugin:631:140)
at e.handleEvent (app.js:1:1170549)
在系统文件管理器打开：
Uncaught TypeError: Cannot read properties of undefined (reading 'path')
at eval (plugin:attachment-flow-plugin:633:36)
at e.handleEvent (app.js:1:1170549)
在文件中显示：
Uncaught TypeError: Cannot read properties of undefined (reading 'path')
at eval (plugin:attachment-flow-plugin:636:76)
at e.handleEvent (app.js:1:1170549)

**Comment by likemuuxi** [comment]
已关闭其他所有插件调试
图片链接：`![[../../Apparatus/Attachments/Assets/UML-240124-1.png]]`
控制台消息：
复制到剪切板：
plugin:attachment-flow-plugin:237 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'vault')
    at eval (plugin:attachment-flow-plugin:237:25)
    at Generator.next (<anonymous>)
    at eval (plugin:attachment-flow-plugin:40:61)
    at new Promise (<anonymous>)
    at __async (plugin:attachment-flow-plugin:24:10)
    at handlerCopyFile (plugin:attachment-flow-plugin:235:60)
    at AttachFlowPlugin.eval (plugin:attachment-flow-plugin:626:11)
    at Generator.next (<anonymous>)
    at eval (plugin:attachment-flow-plugin:40:61)
    at new Promise (<anonymous>)
使用默认应用打开：
plugin:attachment-flow-plugin:631 Uncaught TypeError: Cannot read properties of undefined (reading 'path')
    at eval (plugin:attachment-flow-plugin:631:140)
    at e.handleEvent (app.js:1:1170549)
在系统文件管理器打开：
Uncaught TypeError: Cannot read properties of undefined (reading 'path')
    at eval (plugin:attachment-flow-plugin:633:36)
    at e.handleEvent (app.js:1:1170549)
 在文件中显示：
 Uncaught TypeError: Cannot read properties of undefined (reading 'path')
    at eval (plugin:attachment-flow-plugin:636:76)
    at e.handleEvent (app.js:1:1170549)

**Comment by Yaozhuwa** [comment]
相对路径的图片引用确有问题，我解决下~

**Comment by Yaozhuwa** [comment]
更新最新 0.2.5 版本，应该能修复了~

**Comment by Yaozhuwa** [comment]
太久没回复，我就默认是解决了~
